apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: amq-subscription
spec:
  channel: 7.10.x
  installPlanApproval: Manual
  name: amq-broker-rhel8
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: "amq-broker-operator.v7.10.2-opr-1"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: amq-operator-group
spec:
  targetNamespaces:
  - amq-test
